;;;mode

(setq auto-mode-alist
      (append '(("\\.C$". c++-mode)
                ("\\.cc$". c++-mode)
                ("\\.hh$". c++-mode)
                ("\\.h_$". c++-mode)
                ("\\.cxx$". c++-mode)
                ("\\.cpp$". c++-mode)
                ("\\.h$". c++-mode)
                ("\\.g$". c++-mode)
                ("\\.sor$". c++-mode)
                ("\\.c$". c-mode)
                ("\\.y$". c-mode)
                ("\\.l$". c++-mode)
                ("\\.js$". java-mode)
                ("\\.vhdl?$". vhdl-mode)
                ("\\tcl$". tcl-mode)
                ("\\tk$".  tcl-mode)
                ("followup". text-mode)
                ("\\\.m$" . matlab-mode)
                ("\\\.md$" . markdown-mode)
                ("\\\.markdown$" . markdown-mode)
                ("\\\.pas$" . pascal-mode)
                ("\\\.py" . python-mode)
                ("\\\.tex$" . latex-mode)
                ("\\\.TEX$" . latex-mode)
                ("\\\.Tex$" . LaTeX-mode)
                ("\\.xml$".  sgml-mode)
                ("\\.session" . emacs-lisp-mode)
                ("gnus" . emacs-lisp-mode)
                ("\.bashrc$". shell-script-mode)
                ("\.muttrc$". shell-script-mode)
                ("\.mime.types$". shell-script-mode)
                ("\.alias$". shell-script-mode)
                ("Config$".  shell-script-mode)
                ("config$".  shell-script-mode)
                ("\.conf$".  shell-script-mode)
		;;("mutt". uwp-mail-mode)
		("\\.org$". org-mode)
                ("\\.ctl$" . scheme-mode)
                ("\\.fvwm2rc".  fvwm-mode)
                ("\\.seq".  codev-mode))
              auto-mode-alist))

(provide 'init-mode)
;;; init-mode.el ends here 


